version: "3.8"

services:
  cont1-flask:
    depends_on:
      - mariadb
    build:
      context: ./contenedor1
    ports:
      - "5000:5000"
    networks:
      - app-network
  
  cont2-flask:
    build:
      context: ./contenedor2
    ports:
      - "5001:5001"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
